# Example configuration
general:
  swipe_threshold: 50
  key_interval: 0.05
  key_repeat_delay: 0.5
  key_repeat_interval: 0.03333
  keyboard:
    layout: us

modifiers:
  VIM:
    - { key: Alt_L, send_key: false }
  SHIFT:
    - { key: Shift_L }
    - { key: Shift_R }
  CTRL:
    - { key: Control_L }
    - { key: Control_R }
  ALT:
    - { key: Super_L, send_key: Alt_L }
    - { key: Alt_R }
  META:
    - { key: Caps_Lock, send_key: Super_L }
    - { key: Super_R }
  MOUSE_LEFT:
    - { key: mouse:left }

keybinds:
  - key: Next
    on_press: sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume @DEFAULT_SINK@ -2dB

  - key: Prior
    on_press: sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume @DEFAULT_SINK@ +2dB

  - key: h
    modifiers: [VIM]
    on_press: [+Left]

  - key: j
    modifiers: [VIM]
    on_press: [+Down]

  - key: k
    modifiers: [VIM]
    on_press: [+Up]

  - key: l
    modifiers: [VIM]
    on_press: [+Right]

  - key: i
    modifiers: [VIM]
    on_press: [+Henkan_Mode]

  - key: o
    modifiers: [VIM]
    on_press: [+Muhenkan]

  - key: mouse:forward
    modifiers: [MOUSE_LEFT]
    on_press: [+Control_L, w]

  - key: mouse:backward
    modifiers: [MOUSE_LEFT]
    on_press: [+Alt_L, F4]

gesturebinds:
  - gesture: swipe
    fingers: 3
    direction: up
    on_forward: [+Super_L, Tab]

  - gesture: swipe
    fingers: 3
    direction: down
    on_forward: [+Control_L, w]

  - gesture: swipe
    fingers: 3
    direction: right
    on_forward: [mouse:backward]

  - gesture: swipe
    fingers: 3
    direction: left
    on_forward: [mouse:forward]

  - gesture: swipe
    fingers: 4
    direction: down
    on_forward: [+Alt_L, F4]

  - gesture: swipe
    fingers: 4
    direction: left
    repeat: true
    on_forward: sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume @DEFAULT_SINK@ -2dB
    on_backward: sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume @DEFAULT_SINK@ +2dB

  - gesture: swipe
    fingers: 4
    direction: right
    repeat: true
    on_forward: sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume @DEFAULT_SINK@ +2dB
    on_backward: sudo -u '#1000' XDG_RUNTIME_DIR=/run/user/1000 pactl set-sink-volume @DEFAULT_SINK@ -2dB
